version: '3.8'

services:
  web:
    image: yandexsearchapp:latest
    build:
      context: .
      dockerfile: YandexSearch.Dockerfile
    ports:
      - "5400:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
