version: '3.8'

services:
  web:
    image: yandexsearchapp:latest
    build:
      context: .
      dockerfile: YandexSearch.Dockerfile
    ports:
      - "5400:8080"  
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SELENIUM_HUB_URL=http://selenium:4444/wd/hub  
    networks:
      - app-network
    depends_on:
      - selenium  

  selenium:
    image: selenium/standalone-chrome:latest  
    networks:
      - app-network
    ports:
      - "4444:4444"  

networks:
  app-network:
    driver: bridge
